### ISSUE TITLE
Setting/Updating section header for specific section

### ISSUE THREAD

**Issue by EngrAhsanAli** [DenTelezhkin/DTTableViewManager#74]
Hi!

I am fetching data from web API, and appending in a specific tableView section. So I have the scenario when I get results for _section 1_ before for _section 0_.

How to set/update **setSectionHeaderModels** for specific index. I am considering updating section title (data) after getting response from the web api.

**Comment by DenTelezhkin** [comment]
Hi!

You should probably store section header models in your view model or view controller depending on your architecture. Then, update headerModelProvider on MemoryStorage:

```swift
manager.memoryStorage.headerModelProvider = { index in return <headerModel by index>}
```

Then call reloadData:

```swift
tableView.reloadData()
```

This is needed, because `UITableView` does not have explicit API for updating only headers/footers.

Also, consider updating data when you've already received both API responses, this may lead to more consistent behavior and UI.
